version: '3.8'

services:
  quiz-widget:
    build: .
    ports:
      - "3000:80"
    volumes:
      # Mount your custom quiz.json file
      - ./quiz.json:/usr/share/nginx/html/quiz.json:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  # Optional: Development mode with hot reload
  quiz-widget-dev:
    build: 
      context: .
      target: builder
    ports:
      - "3001:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    profiles:
      - dev
